before_install:
  - gem install bundler

rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - 2.0.0
 - ruby-head
 - ree

notifications:
  webhooks:
    urls:
      - https://hook.ap01.aws.af.cm/travisci
    on_success: always
    on_failure: always
    on_start: false
